version: '3.8'

services:

  nginx:
    restart: unless-stopped
    container_name: nginx
    depends_on:
      - php
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        - INSTALL_DIR=app
        - NGINX_VERSION=1.20
    volumes:
      - "./public:/srv/app/public"
      - "php_socket:/var/run/php"
    ports:
      - "8080:80"

  php:
    container_name: php
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=dev
        - PHP_VERSION=8.1.5
        - INSTALL_DIR=app
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - "php_socket:/var/run/php:rw"
      - "./:/srv/app"
      - "./.docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini:ro"

volumes:
  php_socket: