ARG NGINX_VERSION=1.20
FROM nginx:${NGINX_VERSION}-alpine AS sms-nginx

# Nginx conf
COPY ./.docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY --chown=www-data:www-data ./public /srv/app/public

VOLUME /var/run/php